import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import CustomApolloProvider from "@/lib/apollo-client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <CustomApolloProvider>
      <Toaster theme="dark" position="top-center"/>
        <body className="bg-zinc-100">
          {children}
        </body>
      </CustomApolloProvider>
    </html>
  );
}
